### ISSUE TITLE
Question about tdb

### ISSUE THREAD

**Issue by csantos1113** [next-boost/next-boost-hdc-adapter#1]
Hi @rjyo - quick question about `tdb`. why is it defined to be `Math.min` between what is sent as configuration parameter, and 3600:
https://github.com/rjyo/next-boost-hdc-adapter/blob/abccb920c7993e605e28f3419e66b6df0dc6daaf/src/index.ts#L36

Thank you!

**Comment by rjyo** [comment]
The cache will do the cleanup when `tbd` is reached.  And that operation will lock index DB (Sqlite3) for some time when no read operation can be executed. And depending on the index size, the time could be several ms or much longer. 

Due to this, I think 3600 seconds should be small enough.

**Comment by csantos1113** [comment]
Thanks for clarifying!
